# Generated by Django 6.1 on 2026-08-26 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('email', 'Correo'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('asunto', models.CharField(blank=True, help_text='Solo aplica para plantillas de correo', max_length=200)),
                ('cuerpo', models.TextField(help_text='Usa variables como {nombre_empresa} y {producto} para personalizar el mensaje')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Incluir indicativo de país, ej: +57 300 1234567', max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('fuente', models.CharField(choices=[('hunter', 'Hunter.io'), ('apollo', 'Apollo'), ('procolombia', 'Procolombia'), ('camara_comercio', 'Cámara de comercio'), ('linkedin', 'LinkedIn Sales Navigator'), ('manual', 'Manual'), ('otro', 'Otro')], default='manual', max_length=30)),
                ('estado', models.CharField(choices=[('por_contactar', 'Por contactar'), ('contactado', 'Contactado'), ('interesado', 'Interesado'), ('descartado', 'Descartado'), ('cliente', 'Cliente')], default='por_contactar', max_length=20)),
                ('notas', models.TextField(blank=True, verbose_name='Notas de seguimiento')),
                ('fecha_ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compradores_asignados', to=settings.AUTH_USER_MODEL)),
                ('productos_interes', models.ManyToManyField(blank=True, related_name='compradores_interesados', to='prospeccion.producto')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio', models.CharField(choices=[('email', 'Correo'), ('whatsapp', 'WhatsApp'), ('telefono', 'Teléfono'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='email', max_length=20)),
                ('resultado', models.TextField(blank=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='prospeccion.comprador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de contacto',
                'verbose_name_plural': 'Historial de contactos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='comprador',
            index=models.Index(fields=['estado'], name='prospeccion_estado_b56a92_idx'),
        ),
        migrations.AddIndex(
            model_name='comprador',
            index=models.Index(fields=['pais'], name='prospeccion_pais_437abd_idx'),
        ),
        migrations.AddIndex(
            model_name='comprador',
            index=models.Index(fields=['sector'], name='prospeccion_sector_f86d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='comprador',
            index=models.Index(fields=['fuente'], name='prospeccion_fuente_073797_idx'),
        ),
    ]
