# Generated by Django 6.1 on 2026-08-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
    ]
