# Generated by Django 6.1 on 2026-08-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0002_comprador_facebook_url_comprador_instagram_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='fuente',
            field=models.CharField(choices=[('hunter', 'Hunter.io'), ('apollo', 'Apollo'), ('procolombia', 'Procolombia'), ('camara_comercio', 'Cámara de comercio'), ('linkedin', 'LinkedIn Sales Navigator'), ('ia', 'Búsqueda con IA'), ('manual', 'Manual'), ('otro', 'Otro')], default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='BusquedaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.CharField(max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resultados', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Búsqueda con IA',
                'verbose_name_plural': 'Búsquedas con IA',
                'ordering': ['-creado_en'],
            },
        ),
    ]
