# Generated by Django 6.1 on 2026-08-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0003_alter_comprador_fuente_busquedaia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='fuente',
            field=models.CharField(choices=[('hunter', 'Hunter.io'), ('apollo', 'Apollo'), ('procolombia', 'Procolombia'), ('camara_comercio', 'Cámara de comercio'), ('linkedin', 'LinkedIn Sales Navigator'), ('ia', 'Búsqueda con IA'), ('facebook_ads', 'Facebook Ads'), ('instagram_ads', 'Instagram Ads'), ('manual', 'Manual'), ('otro', 'Otro')], default='manual', max_length=30),
        ),
    ]
