# Generated by Django 6.1 on 2026-08-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0004_alter_comprador_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='condiciones_venta',
            field=models.TextField(blank=True, help_text='Ej. venta en bloque, venta por categorías, colateral financiero — con sus montos y plazos.', verbose_name='Condiciones / escenarios de venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='confidencial',
            field=models.BooleanField(default=False, help_text='Marca este lote como confidencial (documento de origen restringido a su destinatario).'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_contacto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proveedor / consignante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono del proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='referencia',
            field=models.CharField(blank=True, help_text='Código del documento de origen, ej. H11-INV-RCA-001.', max_length=100, verbose_name='Referencia interna'),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valuación/tasación del lote, si es distinta al precio de venta (ej. avalúo antes de descuento).', max_digits=14, null=True, verbose_name='Valor bruto estimado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Precio de venta (referencia)'),
        ),
    ]
