# Generated by Django 6.1 on 2026-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0005_producto_condiciones_venta_producto_confidencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedaia',
            name='error_mensaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='busquedaia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='busquedaia',
            name='fuentes_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busquedaia',
            name='resultados_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
