# Generated by Django 5.2.17 on 2026-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0006_busquedaia_error_mensaje_busquedaia_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='palabras_clave_interes',
            field=models.CharField(blank=True, help_text='Separadas por coma. Ej: "chatarra, motor cummins, vehiculos pesados". Cuando entre un producto nuevo que coincida, se le avisa a este comprador automáticamente.', max_length=300, verbose_name='Palabras clave de interés'),
        ),
    ]
