# Generated by Django 5.2.17 on 2026-09-15 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccion', '0007_comprador_palabras_clave_interes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedaia',
            name='tipo',
            field=models.CharField(choices=[('comprador', 'Buscar compradores'), ('proveedor', 'Buscar proveedores/consignantes')], default='comprador', max_length=20),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Incluir indicativo de país, ej: +57 300 1234567', max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('fuente', models.CharField(choices=[('chatarreo', 'Chatarreo'), ('ia', 'Búsqueda con IA'), ('manual', 'Manual'), ('otro', 'Otro')], default='manual', max_length=30)),
                ('estado', models.CharField(choices=[('por_contactar', 'Por contactar'), ('contactado', 'Contactado'), ('negociando', 'Negociando'), ('consigno', 'Consignó inventario'), ('descartado', 'Descartado')], default='por_contactar', max_length=20)),
                ('notas', models.TextField(blank=True, verbose_name='Notas de seguimiento')),
                ('fecha_ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContactoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio', models.CharField(choices=[('email', 'Correo'), ('whatsapp', 'WhatsApp'), ('telefono', 'Teléfono'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='email', max_length=20)),
                ('resultado', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='prospeccion.proveedor')),
            ],
            options={
                'verbose_name': 'Historial de contacto (proveedor)',
                'verbose_name_plural': 'Historial de contactos (proveedores)',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['estado'], name='prospeccion_estado_2e1d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['pais'], name='prospeccion_pais_06c89c_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['sector'], name='prospeccion_sector_a6fd35_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['fuente'], name='prospeccion_fuente_acf997_idx'),
        ),
    ]
